
# H2 properties
spring:
  datasource:
    url: jdbc:h2:mem:microservices;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: true
    format-sql: true
    # JPA tries to insert data before creating table structure, add this line to solve the issue
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy








