openai:
  model: gpt-3.5-turbo
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions

# Mysql properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: eloualijv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true